import Head from 'next/head'
import Image from 'next/image'
import { useContext, useEffect, useRef } from 'react'
import styles from '../../styles/Home.module.scss'
import Background from '../components/Background.'
import FirstPage from '../components/FirstPage'
import NFTDisplay from '../components/NFTDisplay'
import { ScrollContext } from '../contexts/ScrollContext';

export default function Home() {
	let { setPageHeight } = useContext(ScrollContext);
	const pageRef = useRef(0);

	useEffect(() => {
		setPageHeight(pageRef.current.offsetHeight);
	}, []);

	useEffect(() => {
		const resizeMethod = () => {
			setPageHeight(pageRef.current.offsetHeight);
		}
		window.addEventListener('resize', resizeMethod);
		return () => window.removeEventListener('resize', resizeMethod);
	}, []);


	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main} ref={pageRef}>
				<Background />
				<FirstPage />
				<NFTDisplay />
			</main>

			{/* <footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer> */}
		</div>
	)
}
